import type {CatalogDetail,EntityRecord,MixRecord} from '@syco23/mixsets-domain';
import type {MixSet,ProviderId} from '../domain/types';
import {mediaUrl} from './api';
export type MixSetView=MixSet&{revision:number;missingFields:string[];artistIds:string[];crewIds:string[];eventIds:string[];labelIds:string[]};
export const fieldLabel=(field:string)=>({artistIds:'artists',crewIds:'crew/system',labelIds:'labels',eventIds:'events',recordedAt:'recording date',uploadedAt:'upload date',durationMs:'duration',genres:'genre',realName:'real name',crewLogo:'crew logo',labelLogo:'label logo',organizerIds:'organizers',possibleDuplicate:'possible duplicate',verification:'identity confirmation'}[field]||field);
export function toMixView(detail:CatalogDetail):MixSetView{
 const record=detail.record;if(record.category!=='mix')throw new Error('Record is not a mix');
 const entities=detail.related.filter((r):r is EntityRecord=>r.category==='entity'),names=(ids:string[])=>ids.map(id=>entities.find(r=>r.id===id)?.displayName).filter((name):name is string=>!!name);
 const source=record.sources.filter(ref=>ref.provider!=='web'),claims=detail.claims.filter(c=>['selected','corroborated'].includes(c.state));
 return {id:record.id,title:record.title,revision:record.revision,artistIds:record.artistIds,crewIds:record.crewIds,eventIds:record.eventIds,labelIds:record.labelIds,artists:names(record.artistIds),crews:names(record.crewIds),event:record.eventIds.map(id=>{const event=detail.related.find(r=>r.id===id);return event?.category==='event'?event.name:'';}).filter(Boolean).join(' · ')||undefined,venue:record.venue,location:record.location,recordedAt:record.recordedAt?.value,durationMs:record.durationMs||0,description:record.description,genres:record.genres,styles:record.styles,bpmRange:record.bpmRange,loudnessLufs:record.loudnessLufs,artwork:record.artwork.map(a=>({url:mediaUrl(a.url)!,kind:'cover',source:(a.source==='curator'||a.source==='analysis'?'local':a.source)||'local'})),sources:source as MixSet['sources'],streamUrl:record.streamUrl,fileUrl:record.fileUrl,waveform:record.waveform?{imageDataUrl:mediaUrl(record.waveform.url)!,analyzedAt:record.waveform.analyzedAt||record.updatedAt,sourceUrl:record.waveform.sourceUrl||source[0]?.url||''}:undefined,externalIds:Object.fromEntries(source.filter(s=>s.externalId).map(s=>[s.provider,s.externalId!])),entities:entities.flatMap(e=>e.roles.map(kind=>({kind,name:e.displayName,provider:e.sources.find(s=>s.provider!=='web')?.provider as ProviderId|undefined,externalId:e.sources[0]?.externalId,url:e.sources[0]?.url,profile:e.profile,imageUrl:mediaUrl(e.portrait?.url||e.crewLogo?.url||e.labelLogo?.url)}))),candidates:[],confidence:claims.length?Math.min(...claims.map(c=>c.confidence)):0,completeness:detail.completeness,provenance:claims.filter(c=>!['curator','analysis'].includes(c.provider)).map(c=>({provider:c.provider as ProviderId,field:c.field,confidence:c.confidence,observedAt:c.observedAt,sourceUrl:c.sourceUrl})),status:record.reviewState,createdAt:record.createdAt,updatedAt:record.updatedAt,missingFields:detail.missingFields};
}
