import type { ImportJob, MixSet, ProviderHealth } from './types';

const now = new Date().toISOString();

export const mixes: MixSet[] = [
  {
    id: 'spiral-warehouse-2001',
    title: 'Warehouse Transmission — London 2001',
    artists: ['Ixindamix'],
    crews: ['Spiral Tribe'],
    event: 'Warehouse Transmission',
    venue: 'Unknown warehouse',
    location: 'London, UK',
    recordedAt: '2001-06-09',
    durationMs: 6_574_000,
    description: 'Long-form live recording surfaced through archive sources and cross-enriched against artist and crew records.',
    genres: ['Techno'],
    styles: ['Freetekno', 'Tribe'],
    bpmRange: [150, 168],
    loudnessLufs: -11.8,
    artwork: [{ url: 'https://picsum.photos/seed/syco-spiral/900/900', source: 'local', kind: 'cover' }],
    sources: [
      { provider: 'freeteknomusic', url: 'https://archive.freeteknomusic.org/' },
      { provider: 'discogs', url: 'https://www.discogs.com/' },
    ],
    externalIds: { discogsArtist: 'spiral-tribe' },
    entities: [],
    candidates: [
      {
        id: 'cand-sc-01',
        provider: 'soundcloud',
        confidence: 0.86,
        reasons: ['artist token match', 'duration within 4%', 'event phrase overlap'],
        fields: { event: 'Warehouse 2001', genres: ['Techno', 'Freetekno'] },
        state: 'pending',
      },
    ],
    confidence: 0.92,
    completeness: 0.88,
    provenance: [
      { provider: 'freeteknomusic', field: 'title', confidence: 0.96, observedAt: now },
      { provider: 'discogs', field: 'crews', confidence: 0.91, observedAt: now },
    ],
    status: 'review',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'metek-aniane-98',
    title: 'Aniane Live 98',
    artists: ['Metek'],
    crews: ['Metek Sound System'],
    event: 'Aniane',
    location: 'France',
    recordedAt: '1998-01-01',
    durationMs: 5_392_000,
    description: 'Archive-origin long mix with unusually strong filename evidence.',
    genres: ['Hardtek'],
    styles: ['Live PA', 'Tribe'],
    bpmRange: [155, 176],
    loudnessLufs: -10.9,
    artwork: [{ url: 'https://picsum.photos/seed/syco-metek/900/900', source: 'local', kind: 'cover' }],
    sources: [{ provider: 'freeteknomusic', url: 'https://archive.freeteknomusic.org/metek' }],
    externalIds: {},
    entities: [],
    candidates: [],
    confidence: 0.97,
    completeness: 0.79,
    provenance: [{ provider: 'freeteknomusic', field: 'identity', confidence: 0.97, observedAt: now }],
    status: 'ready',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'novabase-live-tech',
    title: 'NVBS Live Tech 07',
    artists: ['Novabase'],
    crews: ['NVBS'],
    recordedAt: '2007-01-01',
    durationMs: 4_826_000,
    genres: ['Techno'],
    styles: ['Live', 'Hardtek'],
    artwork: [{ url: 'https://picsum.photos/seed/syco-nvbs/900/900', source: 'local', kind: 'cover' }],
    sources: [
      { provider: 'freeteknomusic', url: 'https://archive.freeteknomusic.org/novabase' },
      { provider: 'archiveorg', url: 'https://archive.org/' },
    ],
    externalIds: {},
    entities: [],
    candidates: [],
    confidence: 0.82,
    completeness: 0.62,
    provenance: [{ provider: 'freeteknomusic', field: 'title', confidence: 0.9, observedAt: now }],
    status: 'review',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'gotek-roma-2007',
    title: 'Live @ NBT Party Roma 03.03.07',
    artists: ['Gotek'],
    crews: ['Exfintek'],
    event: 'NBT Party',
    location: 'Roma, Italy',
    recordedAt: '2007-03-03',
    durationMs: 5_841_000,
    genres: ['Hardtek'],
    styles: ['Live', 'Tribe'],
    artwork: [{ url: 'https://picsum.photos/seed/syco-gotek/900/900', source: 'local', kind: 'cover' }],
    sources: [{ provider: 'freeteknomusic', url: 'https://archive.freeteknomusic.org/gotek' }],
    externalIds: {},
    entities: [],
    candidates: [],
    confidence: 0.89,
    completeness: 0.74,
    provenance: [{ provider: 'freeteknomusic', field: 'identity', confidence: 0.94, observedAt: now }],
    status: 'ready',
    createdAt: now,
    updatedAt: now,
  },
];

export const jobs: ImportJob[] = [
  { id: 'job-1', provider: 'freeteknomusic', label: 'crawl /metek', state: 'running', progress: 68, scanned: 142, found: 34, createdAt: now },
  { id: 'job-2', provider: 'archiveorg', label: 'query freetekno live set', state: 'review', progress: 100, scanned: 80, found: 12, createdAt: now },
  { id: 'job-3', provider: 'soundcloud', label: 'artist: Gotek duration > 30m', state: 'queued', progress: 0, scanned: 0, found: 0, createdAt: now },
];

export const providerHealth: ProviderHealth[] = [
  { id: 'freeteknomusic', name: 'Freeteknomusic Archive', mode: 'discover', state: 'ready', detail: 'HTTP directory crawler · bounded recursion', auth: 'none', lastCheck: now },
  { id: 'soundcloud', name: 'SoundCloud', mode: 'both', state: 'limited', detail: 'Official API · token required for live queries', auth: 'required', lastCheck: now },
  { id: 'archiveorg', name: 'Internet Archive', mode: 'discover', state: 'ready', detail: 'Advanced Search + Metadata API', auth: 'none', lastCheck: now },
  { id: 'discogs', name: 'Discogs', mode: 'enrich', state: 'limited', detail: 'Artist / label / image enrichment', auth: 'optional', lastCheck: now },
  { id: 'youtube', name: 'YouTube', mode: 'both', state: 'limited', detail: 'Public video links work; text search needs an API key', auth: 'optional', lastCheck: now },
  { id: 'hearthis', name: 'hearthis.at', mode: 'both', state: 'ready', detail: 'Public track search and artwork', auth: 'none', lastCheck: now },
];
